server:
  address: 8080

spring:
  jpa:
    database: postgresql
    show-sql: true
    properties:
      hibernate:
        default_schema: shop_schema
  datasource:
    url: jdbc:postgresql://db/shop_db
    driver-class-name: org.postgresql.Driver
    username: admin
    password: admin
