server:
  port: 8080

spring:
  jpa:
    database: postgresql
    show-sql: false
    properties:
      hibernate:
        default_schema: retail
        jdbc.lob.non_contextual_creation: true
        jdbc.batch_size: 30
        order_inserts: true
        order_updates: true
        batch_versioned_data: true
    hibernate:
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
  datasource:
    driver-class-name: org.postgresql.Driver